export const ENV_VARS = {
  PORT: 'PORT',
  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_HOST: 'MONGO_DB_HOST',
  MONGO_DB_DATABASE: 'MONGO_DB_DATABASE',

  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  SMTP_FROM: 'SMTP_FROM',

  JWT_SECRET: 'JWT_SECRET',

  FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
  BACKEND_DOMAIN: 'BACKEND_DOMAIN',

  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',

  FILE_SAVING_STRATEGY: 'FILE_SAVING_STRATEGY',

  GOOGLE__OAUTH_CLIENT_ID: 'GOOGLE__OAUTH_CLIENT_ID',
  GOOGLE__OAUTH_CLIENT_SECRET: 'GOOGLE__OAUTH_CLIENT_SECRET',
  GOOGLE__OAUTH_PROJECT_ID: 'GOOGLE__OAUTH_PROJECT_ID',
  GOOGLE__OAUTH_REDIRECT_URI: 'GOOGLE__OAUTH_REDIRECT_URI',
};
